<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>152a1760-81fc-4500-b383-cd5d4449c4c2</testSuiteGuid>
   <testCaseLink>
      <guid>d1ba1bca-b69f-42dc-a100-f7f1f0635897</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenTestDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2c5009a7-8077-4246-b31b-619020523514</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SampleDataInternal</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2c5009a7-8077-4246-b31b-619020523514</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>usr</value>
         <variableId>0b66ffa1-99d1-45c0-a453-cefa5f479c02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2c5009a7-8077-4246-b31b-619020523514</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>82192979-8fd4-47e4-8075-1e5587d21d67</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c933bc1f-ef31-4480-ac11-1edf130f2e0a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/GitDemo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
