<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_frame-right</name>
   <tag></tag>
   <elementGuidId>66f45176-4d16-4b84-9e0a-9794c35789e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;frame-right&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='frame-right']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>3b7aa342-b416-4aa6-aebb-3c514cdb6778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/frame_right</value>
      <webElementGuid>36f102d8-0d4b-442f-a534-d12f1585e7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>ef282381-3a6a-4e34-849e-adcaf8d6df5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frame-right</value>
      <webElementGuid>b2e29c3c-0492-4044-b28c-03434e762b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[3]</value>
      <webElementGuid>370909ce-0cf8-41ce-8c27-3858c8d0b1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Frame/frame_frame-top</value>
      <webElementGuid>ed3cb720-1545-4606-b9c1-8cca66d9efae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='frame-right']</value>
      <webElementGuid>5eab3f23-33e8-42f5-a241-5a4a175a81a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[3]</value>
      <webElementGuid>f0a0c664-a4d8-4e0b-b8f2-4c3bcc206839</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = '/frame_right' and @name = 'frame-right']</value>
      <webElementGuid>b5bf6ee1-2e0e-4f9b-8a45-df6ba04f3d3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
