<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frame_frame-bottom</name>
   <tag></tag>
   <elementGuidId>873d466c-6e47-4d1a-9ac4-d60aba5da368</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;frame-bottom&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='frame-bottom']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>97dfa52a-b54e-42b7-a88b-feed359b43c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/frame_bottom</value>
      <webElementGuid>8099f4e9-7e71-4759-9ada-6fc08c54fdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>e10007d2-0ba2-490c-a3a6-bb7b9d8b8b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frame-bottom</value>
      <webElementGuid>791352eb-0616-4b29-a4b0-de5c48c87967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[2]</value>
      <webElementGuid>b353177c-606e-4307-a981-60bcc082c8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='frame-bottom']</value>
      <webElementGuid>6721157e-7d0f-4dcc-80e9-0a1295883ca8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>fad838c9-3e84-450d-b3e7-1239d6d2853e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = '/frame_bottom' and @name = 'frame-bottom']</value>
      <webElementGuid>ce6a1f8e-2818-4c9e-a30e-aebe98bf0206</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
