<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Payla_playerId__28250694--57shaka-mock-_44972c</name>
   <tag></tag>
   <elementGuidId>dafa6247-884f-4fc7-9f36-4851baf41067</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value> //div[@id='playerId__28250694--57shaka-mock-vjs-control-bar-popover-area']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#playerId__28250694--57shaka-mock-vjs-control-bar-popover-area</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fda33b8e-dc38-477d-acd9-6a3d0bebeee1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>playerId__28250694--57shaka-mock-vjs-control-bar-popover-area</value>
      <webElementGuid>a9a63959-b92b-409f-a116-ee67edeb2d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>video-popover-area shaka-control-bar--popover-area--1vJ7p</value>
      <webElementGuid>be9f5629-6166-4bb5-89d7-99699bebd219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;playerId__28250694--57shaka-mock-vjs-control-bar-popover-area&quot;)</value>
      <webElementGuid>f095c6f6-ccd9-40ae-bc60-90a98b2812d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='playerId__28250694--57shaka-mock-vjs-control-bar-popover-area']</value>
      <webElementGuid>180f618d-7046-43cf-8fd4-468fc4a78f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//div[@id='playerId__28250694--57shaka-mock-vjs-control-bar']/div)[2]</value>
      <webElementGuid>22569b9f-b31f-4247-9c10-6122aeae7124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/div[2]/div/div</value>
      <webElementGuid>d5e90cec-30dd-43f2-bb26-94805f8f80e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'playerId__28250694--57shaka-mock-vjs-control-bar-popover-area']</value>
      <webElementGuid>30e3c6f0-29c8-46b9-a538-658d724055ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
